# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
    - export BASE_IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')-base-new
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
#    - docker pull "$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG"

stages:
  - base
  - build services

build base:
  tags:
    - dcos-multi-runner
  stage: base
  script:
    - cd base
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG"

build broker:
  tags:
    - dcos-multi-runner
  stage: build services
  script:
    - cd broker; sed -i "s#BASE_IMAGE#$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG#g" Dockerfile
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')-broker
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"

build tranquility:
  tags:
    - dcos-multi-runner
  stage: build services
  script:
    - cd tranquility; sed -i "s#BASE_IMAGE#$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG#g" Dockerfile
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')-tranquility
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"


build historical:
  tags:
    - dcos-multi-runner
  stage: build services
  script:
    - cd historical; sed -i "s#BASE_IMAGE#$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG#g" Dockerfile
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')-historical
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"


build coordinator:
  tags:
    - dcos-multi-runner
  stage: build services
  script:
    - cd coordinator; sed -i "s#BASE_IMAGE#$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG#g" Dockerfile
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')-coordinator
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"


build indexing:
  tags:
    - dcos-multi-runner
  stage: build services
  script:
    - cd indexing/middle-manager; sed -i "s#BASE_IMAGE#$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG#g" Dockerfile
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')-middle
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
    - cd ../../
    - cd indexing/overlord; sed -i "s#BASE_IMAGE#$CI_REGISTRY_IMAGE:$BASE_IMAGE_TAG#g" Dockerfile
    - export IMAGE_TAG=$(echo -en $CI_COMMIT_REF_NAME | tr -c '[:alnum:]_.-' '-')-overlord
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$IMAGE_TAG" .
    - docker push "$CI_REGISTRY_IMAGE:$IMAGE_TAG"
